Soit la base de données de la médiathèque définie tout au long du chapitre.

![](https://capytale2.ac-paris.fr/web/sites/default/files/2021-12-29-13-44-45/livres.png)

## Donner le code `SQL` de chacune des requêtes ci-dessous.

#### 1. Le titre des livres empruntés.

In [1]:
SELECT livre.titre FROM emprunt
JOIN livre ON emprunt.isbn = livre.isbn;

titre
Gargantua et Pantagruel
Les Contes de Canterbury
Le Vieil Homme et la Mer
Mrs Dalloway
Fondation et Empire
Énéide
Les Hauts de Hurlevent
La Planète des singes
Jack Barron et l'Éternité
Les Voyages de Gulliver
Guerre et Paix
Anna Karénine
Les Fils de la Médina
Les Robots
Le Père Goriot
Le Journal d'un fou
Astérix et la Transitalique


#### 2. Le titre des livres empruntés à rendre avant le 31/03/2020.

In [2]:
SELECT titre FROM emprunt
JOIN livre ON emprunt.isbn = livre.isbn
WHERE emprunt.retour <= '2020-03-31';

titre
Guerre et Paix
Les Voyages de Gulliver
Gargantua et Pantagruel
Les Hauts de Hurlevent
Énéide
Astérix et la Transitalique
Les Contes de Canterbury
Le Père Goriot
La Planète des singes
Anna Karénine
Les Robots
Le Vieil Homme et la Mer
Les Fils de la Médina


#### 3. Le nom et prenom de l'auteur du livre ' 1984' .

In [3]:
SELECT auteur.nom, auteur.prenom FROM livre
JOIN auteur_de ON livre.isbn = auteur_de.isbn
JOIN auteur ON auteur.a_id = auteur_de.a_id
WHERE titre = '1984';

nom	prenom
Orwell	George


#### 4. Le nom et le prenom des usagers ayant emprunté des livres, sans doublons.
(i. e. si un usager a emprunté plusieurs livres, il ne doit apparaître qu'une fois dans le résultat).

In [4]:
SELECT DISTINCT usager.nom, usager.prenom FROM emprunt
JOIN usager ON emprunt.code_barre = usager.code_barre;

nom	prenom
MOREAU	ALAIN
DUBOIS	PHILIPPE
ROBERT	PASCAL
LAURENT	FRANÇOISE
SIMON	SANDRINE
PETIT	SÉBASTIEN
BERNARD	STÉPHANE


#### 5. Même requête que précédemment, avec les noms triés par ordre alphabétique.

In [5]:
SELECT DISTINCT nom, prenom FROM emprunt
JOIN usager ON emprunt.code_barre = usager.code_barre
ORDER BY nom, prenom ASC;

nom	prenom
BERNARD	STÉPHANE
DUBOIS	PHILIPPE
LAURENT	FRANÇOISE
MOREAU	ALAIN
PETIT	SÉBASTIEN
ROBERT	PASCAL
SIMON	SANDRINE


#### 6. Les titre des livres publiés strictement avant ' Dune' .

In [6]:
SELECT titre FROM livre
WHERE annee < (SELECT annee FROM livre 
                            WHERE titre = 'Dune');

titre
Fondation et Empire
Akira
Berlin Alexanderplatz
Croisière sans escale
Le Carnet d'or
Astérix et Cléopâtre
1984
Vermilion Sands
Au carrefour des étoiles
Les Buddenbrook
Le Noir Dessein
The Practice of Programming
La Promenade au phare
Le Bruit et la Fureur
Les Plus qu'humains
Mémoires d'Hadrien
Contes de l'absurde
Les Contes de Canterbury
The Art of Computer Programming
L'Aveuglement
Le Domaine des dieux
Cent ans de solitude
Énéide
Seconde Fondation
Les Jeux de l'esprit
Middlemarch
Fictions
Astérix chez les Bretons
Le Tambour
Pedro Páramo
Le monde s'effondre
L'Éducation sentimentale
La Plaie
Astérix chez les Belges
Le Rouge et le Noir


#### 7. Les noms et prenoms des auteurs des livres trouvés à la question précédente.

In [7]:
SELECT auteur.nom, auteur.prenom FROM livre
JOIN auteur_de ON livre.isbn = auteur_de.isbn
JOIN auteur ON auteur.a_id = auteur_de.a_id
WHERE annee < (SELECT annee FROM livre 
                            WHERE titre = 'Dune')
ORDER BY nom;

nom	prenom
Achebe	Chinua
Aldiss	Brian Wilson
Asimov	Isaac
Asimov	Isaac
Ballard	J. G.
Borges	Jorge Luis
Boulle	Pierre
Boulle	Pierre
Chaucer	Geoffrey
Deutsch	Michel
Döblin	Alfred
Eliot	George
Fall	Malick
Farmer	Philip José
Faulkner	William
Fransa	France
Goscinny	René
Goscinny	Rene
Goscinny	René
Goscinny	René
Grass	Günter
Kernighan	Brian W.
Knuth	Donald E.
Lessing	Doris
Mann	Thomas
Márquez	Gabriel García
Orwell	George
Pike	Rob
Rincé	Dominique
Rulfo	Juan
Saramago	José
Simak	Clifford D.
Stendhal
Uderzo	Albert
Uderzo	Albert
Uderzo	Albert
Uderzo	Albert
Vergilius	Publius Maro
Virgile
Woolf	Virginia
Yourcenar	Marguerite
Ōtomo	Katsuhiro


#### 8. Comme la question précédente, en retirant les doublons.

In [8]:
SELECT DISTINCT auteur.nom, auteur.prenom FROM livre
JOIN auteur_de ON livre.isbn = auteur_de.isbn
JOIN auteur ON auteur.a_id = auteur_de.a_id
WHERE annee < (SELECT annee FROM livre 
                            WHERE titre = 'Dune')
ORDER BY nom;

nom	prenom
Achebe	Chinua
Aldiss	Brian Wilson
Asimov	Isaac
Ballard	J. G.
Borges	Jorge Luis
Boulle	Pierre
Chaucer	Geoffrey
Deutsch	Michel
Döblin	Alfred
Eliot	George
Fall	Malick
Farmer	Philip José
Faulkner	William
Fransa	France
Goscinny	René
Goscinny	Rene
Grass	Günter
Kernighan	Brian W.
Knuth	Donald E.
Lessing	Doris
Mann	Thomas
Márquez	Gabriel García
Orwell	George
Pike	Rob
Rincé	Dominique
Rulfo	Juan
Saramago	José
Simak	Clifford D.
Stendhal
Uderzo	Albert
Vergilius	Publius Maro
Virgile
Woolf	Virginia
Yourcenar	Marguerite
Ōtomo	Katsuhiro


#### 9. Le nombre de résultats trouvés à la question précédente.

In [9]:
SELECT COUNT(DISTINCT auteur.nom) FROM livre
JOIN auteur_de ON livre.isbn = auteur_de.isbn
JOIN auteur ON auteur.a_id = auteur_de.a_id
WHERE annee < (SELECT annee FROM livre 
                            WHERE titre = 'Dune');

COUNT(DISTINCT auteur.nom)
34